name: Ejecutar Hola Mundo

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'   # cada minuto

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ejecutar script
        run: python Scripts/holamundo.py

      - name: Mostrar contenido del archivo generado
        run: cat resultado.txt

      - name: Subir archivo como artifact
        uses: actions/upload-artifact@v4
        with:
          name: resultado
          path: resultado.txt